site_name: My Snippets & Notes
site_url: https://sfuller14.github.io/4reference/
site_author: Sean Fuller
site_description: >-
  Notes and code snippets

plugins:
  - search
  - mkdocs_pymdownx_material_extras

theme:
  name: material
  scheme: slate
  custom_dir: material/overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    # - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      scheme: dracula
      primary: '#f8f8f2'       # Dracula foreground
      accent: '#bd93f9'        # Dracula purple
      background: '#282a36'    # Dracula background
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   primary: '#f8f8f2'       # Dracula foreground
    #   accent: '#bd93f9'        # Dracula purple
    #   background: '#282a36'    # Dracula background
    #   text: '#f8f8f2'          # Suggested for primary text, Dracula foreground
    #   code: '#ff79c6'          # Suggested for inline code, Dracula pink
    #   anchor: '#8be9fd'        # Suggested for anchor links, Dracula cyan
    #   anchor_hover: '#50fa7b'  # Suggested for anchor hover, Dracula green
    #   toggle:
    #     icon: material/toggle-switch-off
    #     name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
    
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - toc:
      toc_depth: 2